
CAR_COLOR: !!python/tuple [60, 180, 75]
PS_COLORS:
  - !!python/tuple [230, 25, 75]
  - !!python/tuple [70, 240, 240]
RB_COLOR: !!python/tuple [210, 245, 60]
SO_COLOR: !!python/tuple [255, 250, 200]

LABEL :
   - !!python/tuple [30, 30, 30]
   - !!python/tuple [8, 255, 51]
   - !!python/tuple [180, 120, 120]
   - !!python/tuple [6, 230, 230]
   - !!python/tuple [80, 50, 50]
   - !!python/tuple [4, 200, 3]
   - !!python/tuple [120, 120, 80]
   - !!python/tuple [140, 140, 140]
   - !!python/tuple [204, 5, 255]
   - !!python/tuple [230, 230, 230]
   - !!python/tuple [4, 250, 7]
   - !!python/tuple [224, 5, 255]
   - !!python/tuple [235, 255, 7]
   - !!python/tuple [150, 5, 61]
   - !!python/tuple [120, 120, 70]
   - !!python/tuple [120, 120, 120]
   - !!python/tuple [255, 6, 82]
   - !!python/tuple [143, 255, 140]
   - !!python/tuple [204, 255, 4]
   - !!python/tuple [255, 51, 7]
   - !!python/tuple [204, 70, 3]
   - !!python/tuple [0, 102, 200]
   - !!python/tuple [61, 230, 250]
   - !!python/tuple [255, 6, 51]
   - !!python/tuple [11, 102, 255]
   - !!python/tuple [255, 7, 71]
   - !!python/tuple [255, 9, 224]
   - !!python/tuple [9, 7, 230]
   - !!python/tuple [220, 220, 220]
   - !!python/tuple [255, 9, 92]
   - !!python/tuple [112, 9, 255]
   - !!python/tuple [8, 255, 214]
   - !!python/tuple [7, 255, 224]
   - !!python/tuple [255, 184, 6]
   - !!python/tuple [10, 255, 71]
   - !!python/tuple [255, 41, 10]
   - !!python/tuple [7, 255, 255]
   - !!python/tuple [224, 255, 8]
   - !!python/tuple [102, 8, 255]
   - !!python/tuple [255, 61, 6]
   - !!python/tuple [255, 194, 7]
   - !!python/tuple [255, 122, 8]
   - !!python/tuple [0, 255, 20]
   - !!python/tuple [255, 8, 41]
   - !!python/tuple [255, 5, 153]
   - !!python/tuple [6, 51, 255]
   - !!python/tuple [235, 12, 255]
   - !!python/tuple [160, 150, 20]
   - !!python/tuple [0, 163, 255]
   - !!python/tuple [140, 140, 140]
   - !!python/tuple [250, 10, 15]
   - !!python/tuple [20, 255, 0]
   - !!python/tuple [31, 255, 0]



START_COLOR: !!python/tuple [0, 255, 0]

EXPERT: !!python/tuple [0, 255, 0]
GEN: !!python/tuple [255, 255, 30]
BEST: !!python/tuple [255, 0, 0]
